services:
  backend:
    image: rajatrulaniya/hackdata-backend:latest
    ports:
      - 8000:8000

  frontend:
    image: rajatrulaniya/hackdata-frontend:latest
    environment:
      BACKEND_HOST: hackdata.rajatrulaniya.com
      BACKEND_PORT: 8000
    ports:
      - 80:80
    
    depends_on:
      - backend
